# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='BarterAccount',
            fields=[
                (
                    'id',
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
                ),
                ('patron_name', models.CharField(max_length=100)),
                ('balance', models.IntegerField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BarterEvent',
            fields=[
                (
                    'id',
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
                ),
                (
                    'event_type',
                    models.CharField(
                        choices=[('Add', 'Add'), ('Subtract', 'Subtract'), ('Note', 'Note')],
                        default='Subtract',
                        max_length=20
                    )
                ),
                ('event_time', models.DateTimeField(auto_now_add=True)),
                (
                    'barter_account',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='bartercheckout.BarterAccount'
                    )
                ),
            ],
        ),
    ]
