# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bartercheckout', '0002_auto_20170728_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='barterevent',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='barteraccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
