# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 00:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bartercheckout', '0003_auto_20170729_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barteraccount',
            old_name='patron_name',
            new_name='customer_name',
        ),
    ]
