# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bartercheckout', '0004_auto_20170730_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='barteraccount',
            name='last_add',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='barteraccount',
            name='last_subtract',
            field=models.DateField(null=True),
        ),
    ]
