# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bartercheckout', '0005_auto_20170730_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barteraccount',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
