# Generated by Django 2.1.7 on 2019-03-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bartercheckout', '0009_change_account_balance_to_dollars_and_cents'),
    ]

    operations = [
        migrations.AddField(
            model_name='barterevent',
            name='initials',
            field=models.CharField(default='', max_length=20),
        ),
    ]
